!obj:pylearn2.train.Train {
    dataset: &train !obj:pylearn2.datasets.csv_dataset.CSVDataset {
      path: './train.csv',
      task: 'classification',
      expect_labels: True,
      expect_headers: False,
      delimiter: ',',
      start_fraction: 0.9,
},
    model: !obj:pylearn2.models.softmax_regression.SoftmaxRegression {
    n_classes: 2,
    irange: 0.,
    nvis: 10,
}
,
    algorithm: !obj:pylearn2.training_algorithms.sgd.SGD {
        batch_size: 5 ,
        learning_rate: .1,
        monitoring_dataset:
            {
                'train' : *train,
                'valid' : !obj:pylearn2.datasets.csv_dataset.CSVDataset {
                                path: './train.csv',
                                expect_headers: False,
                                start_fraction: .9,
                          },
                'test'  : !obj:pylearn2.datasets.csv_dataset.CSVDataset {
                                path: './train.csv',
                                expect_headers: False,
                                end_fraction: .1,
                          }
            },
        termination_criterion: !obj:pylearn2.termination_criteria.MonitorBased {
            channel_name: "valid_y_misclass"
        }
    },
    extensions: [
        !obj:pylearn2.train_extensions.best_params.MonitorBasedSaveBest {
             channel_name: 'valid_y_misclass',
             save_path: "./softmax_regression_best.pkl"
        },
    ],
    save_path: "./softmax_regression.pkl",
    save_freq: 1
}